- name: Deploy App using Docker Compose
  hosts: all
  become: true
  vars_files:
    - "../group_vars/all/vars.yml"
    - "../group_vars/all/vault.yml"
  tasks:
    - name: ECR Login
      shell: "aws ecr get-login-password --region {{ region }} | docker login --username AWS --password-stdin {{ ecr_registry }}"
      changed_when: false
      become: true

    #- name: Pull And start container
      #shell: |
        #docker compose -f /opt/flask-app/docker-compose.yml pull
        #docker compose -f /opt/flask-app/docker-compose.yml up -d --remove-orphans
      #args:
        #hdir: /opt/flask-app

    - name: Deploy with Docker Compose
      community.docker.docker_compose_v2:
         project_src: /opt/flask-app
         state: present
         pull: always
         remove_orphans: yes
      become: true