
- name: Prepare Servers for Docker(Docker-Compose) & ECR
  hosts: all
  become: true
  vars_files:
    - "../group_vars/all/vars.yml"
    - "../group_vars/all/vault.yml"
  
  tasks:
    - name: Check if vars are loaded
      debug:
        var: hostvars[inventory_hostname]

    
    - name: Make sure universe repository is enabled
      ansible.builtin.apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe
        state: present
        update_cache: true

    - name: Wait for any possible APT locks to release
      shell: while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 5; done;
      changed_when: false

    - name: Update apt and install relevant libraries
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          #- python3-pip
          #- unzip
          #- python3-docker
        state: present
        update_cache: yes

    #- name: Add Docker GPG Key
      #apt_key:
        #url: https://download.docker.com/linux/ubuntu/gpg
        #state: present
    
    #- name: Add Docker Repository
      #apt_repository:
        #repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        #state: present

    - name: Install Docker
      shell: |
        set -e
        curl -fsSl https://get.docker.com -o get-docker.sh
        chmod +x get-docker.sh
        ./get-docker.sh
      become: true
      register: docker_script_output
      #args:
        #creates: /usr/bin/docker

    - name: Debug Docker script output
      debug:
        var: docker_script_output.stdout_lines 

    - name: Setup Python-pip & Docker-python
      shell: |
        apt-get clean
        apt-get update 
        apt-get install -y \
           python3-pip \
           python3-docker \
           unzip
      become: true
      register: final_install
      until: final_install is success
      retries: 2
      delay: 10
    
    - name: Daemon reload for new services
      shell: |
        systemctl daemon-reload
        systemctl enable docker
        systemctl start docker
      become: true

    - name: Ensure Docker group exists
      ansible.builtin.group:
        name: docker
        state: present

    #- name: Ensure Docker is running and enabled
      #ansible.builtin.systemd:
        #name: docker
        #state: started
        #enabled: yes
        #daemon_reload: yes
      #become: true

    - name: Verify Docker with quick cmd
      shell: docker ps
      register: docker_check
      changed_when: false
      become: true

    - name: Show Docker status
      debug:
        var: docker_check.stdout_lines

    - name: Add ssm-user to docker group
      user:
        name: ssm-user
        groups: docker
        append: yes

    - name: Install AWS CLI
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -o awscliv2.zip
        ./aws/install --update
      args:
        creates: /usr/local/bin/aws

    - name: Create Directory For App
      file:
        path: /opt/flask-app
        state: directory
        owner: ssm-user
        group: docker
        mode: '0755'

    - name: Deploy docker-compose from template
      template:
        src: ../templates/docker-compose.yml.j2
        dest: /opt/flask-app/docker-compose.yml
        owner: ssm-user
        group: docker
        mode: '0644'