name: Tf-Sec-Provision

on:
    workflow_run:
        workflows:
            - "Build-Push"
        branches:
            - main
        types:
            - completed
    workflow_dispatch:
permissions:
    id-token: write
    contents: read

jobs:
    Security-Scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Run tfsec
              uses: aquasecurity/tfsec-action@v1.0.3
              with:
                soft_fail: false

            - name: Configure AWS Creds
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                aws-region: ${{ vars.AWS_REGION }}
                role-session-name: GitHubActions-Security-Scan

            - name: Validare IAM Policies
              id: iam-validator
              uses: aws-actions/terraform-aws-iam-policy-validator@v1.0.0
              with:
                policy-check-type: 'VALIDATE_POLICY'
                template-path: 'terraform-infra/iam.tf'
                region: ${{ vars.AWS_REGION }}
                args: --output-file terraform-infra/validation-logs.txt
            
            - name: Upload Policy validation report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: iam-policy-report
                path: "**/validation-logs.txt"
                retention-days: 1

  