name: Tf-Sec-Provision

on:
    workflow_run:
        workflows:
            - "Build-Push"
        branches:
            - main
        types:
            - completed
    workflow_dispatch:
permissions:
    id-token: write
    contents: read

jobs:
    Security-Scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Setup terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: "1.14.4"

            - name: Run tfsec
              uses: aquasecurity/tfsec-action@v1.0.3
              with:
                soft_fail: false

            - name: Configure AWS Creds
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                aws-region: ${{ vars.AWS_REGION }}
                role-session-name: GitHubActions-Security-Scan      
            
            - name: Create temp .tfvars
              run: |
                echo 'SLACK_WEBHOOK_URL = "'"${{ secrets.SLACK_WEBHOOK_URL }}"'"' > terraform-infra/temp.tfvars
                echo 'ansible_vault_pass = "'"${{ secrets.ANSIBLE_VAULT_PASS_ARN }}"'"' >> terraform-infra/temp.tfvars
                echo 'azs = "'"${{ vars.AZS }}"'"' >> terraform-infra/temp.tfvars
                echo 'db_username = "'"${{ secrets.DB_USERNAME }}"'"' >> terraform-infra/temp.tfvars
                echo 'rds_password = "'"${{ secrets.DB_PASS }}"'"' >> terraform-infra/temp.tfvars
                echo 'default_region = "'"${{ vars.AWS_REGION }}"'"' >> terraform-infra/temp.tfvars
                echo 'enable_waf = "false"' >> terraform-infra/temp.tfvars
                echo 'environment = "DEV"' >> terraform-infra/temp.tfvars
                echo 'project_name = "flask-project"' >> terraform-infra/temp.tfvars
                echo 'python_version = "3.9"' >> terraform-infra/temp.tfvars
                echo 'instance_type = "t3.micro"' >> terraform-infra/temp.tfvars
                echo 'key_name = "'"${{ vars.KEY_NAME }}"'"' >> terraform-infra/temp.tfvars
                echo 'pub_key_path = "'"$(echo "${{ secrets.PUB_KEY_PATH }}" | tr -d '\n')'"'"' >> terraform-infra/temp.tfvars
                echo 'my_mail = "shuamglebshi@gmail.com"' >> terraform-infra/temp.tfvars
                echo 'vpc_cidr = "'"${{ secrets.VPC_CIDR }}"'"' >> terraform-infra/temp.tfvars


            

            - name: Prepare And Launch Tf
              run: |
                terraform init -reconfigure &&
                terraform plan -var-file=temp.tfvars -out=tfplan &&
                terraform show -json tfplan > tfplan.json
              working-directory: terraform-infra


            - name: Remove temp .tfvars
              run: |
                rm -rf terraform-infra/temp.tfvars


            - name: Prepare report Dir
              run: mkdir -p terraform/reports

            - name: Validate IAM Policies
              id: iam-validator
              uses: aws-actions/terraform-aws-iam-policy-validator@v1.0.0
              with:
                policy-check-type: 'VALIDATE_POLICY'
                template-path: 'terraform-infra/tfplan.json'
                region: ${{ vars.AWS_REGION }}
                args: --output-file terraform/reports/validation-logs.txt
            
            - name: Upload Policy validation report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: iam-policy-report
                path: terraform/reports/validation-logs.txt
                retention-days: 1

  
